version: '3'
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=elearnio
      - POSTGRES_PASSWORD=elearnio
      - POSTGRES_DB=elearnio
      - DATABASE_HOST=db-host
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
    depends_on:
      - db
